steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/rare-mender-305609/pendu-run:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/rare-mender-305609/pendu-run:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'rare-mender-305609', '--region=europe-west1', '--platform=managed', '--image=gcr.io/rare-mender-305609/pendu-run:$SHORT_SHA']   
   
